services:

  api:
    build: .
    container_name: addiction_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build: .
    container_name: addiction_streamlit
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app